export const Conclusions = () => {
  return (
    <div className="page_container">
      <h1>Conclusions</h1>
      <h3>The First Law of Thermodynamics</h3>
      <p>
        "The First Law of Thermodynamics states the conservation of energy,
        which in the context of heat transfer means that the total energy
        entering or leaving a system must be equal to the change in the system's
        internal energy plus the work done on the system."
      </p>

      <>
        <div className="firstLaw">
          <p>
            <strong>First Law of Thermodynamics:</strong>
          </p>
          <p>
            The First Law of Thermodynamics, also known as the principle of
            conservation of energy, states that energy cannot be created or
            destroyed, only transformed from one form to another. In the context
            of heat transfer, the First Law can be expressed mathematically as
            follows:
          </p>
          <label>Q = ΔU + W</label>
          <br />
          <br />
          <label>Where:</label>
          <ul>
            <li>
              <b>Q</b> is the amount of heat transferred to the system.
            </li>
            <li>
              <b>ΔU</b> is the change in internal energy of the system.
            </li>
            <li>
              <b>W</b> is the work done on the system.
            </li>
          </ul>
          <p>
            This equation states that the amount of heat transferred to a system
            is equal to the change in its internal energy plus the work done on
            the system. It is one of the fundamental principles of
            thermodynamics and applies to a wide range of situations in physics
            and engineering.
          </p>
        </div>
      </>

      <h3>This case:</h3>
      <p>
        In this case, the system is the engine and the surrounding environment.
        The energy entering the system is the power generated by the engine, and
        due to the engine's efficiency, a portion of this energy is dissipated
        in the form of heat. <br />
        <br />
        When calculating the heat transfer by convection and radiation
        separately, while varying both <b>h</b> and <b>ε</b>, we are considering
        the amount of thermal energy transferred to the environment through
        these two mechanisms. <br />
        When the heat transfer by convection and radiation is summed, it takes
        into account the total thermal energy that the engine is losing in the
        form of heat to the environment. <br />
        <br />
        The sum of heat transfer by convection and radiation must match the
        total energy loss of the engine due to its inefficiency, which complies
        with the principle of energy conservation according to the First Law of
        Thermodynamics, this can be evidenced in the graphs of the section 'P
        <sub>i</sub> Q&#x0307;<sub>conv</sub> Q&#x0307;<sub>rad</sub> v.s. h &
        𝜺'.
      </p>
      <br />
      <br />
    </div>
  );
};
